# Generated by Django 4.1 on 2022-08-21 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='نام')),
                ('last_name', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='پیام')),
                ('is_seen_by_manager', models.BooleanField(default=False, verbose_name='وضعیت پیام')),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'db_table': 't_message',
            },
        ),
    ]
