# Generated by Django 4.1.2 on 2022-11-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogidea_dislike_like_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogidea',
            options={'verbose_name': 'BlogIdea', 'verbose_name_plural': 'BlogIdeas'},
        ),
        migrations.AlterModelTable(
            name='blogidea',
            table='table_BlogIdea',
        ),
    ]
