# Generated by Django 4.1.2 on 2022-11-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogidea_options_alter_blogidea_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogidea',
            name='blog_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='blog_slug'),
        ),
    ]
