# Generated by Django 4.1.2 on 2022-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogidea_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogidea',
            name='blog_idea',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='blogidea',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='blogidea',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
