# Generated by Django 4.1 on 2022-08-26 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('article_slug', models.SlugField(max_length=200, verbose_name='کلید مقاله')),
                ('article_summery', models.TextField(verbose_name='خلاصه مقاله')),
                ('article_text', models.TextField(verbose_name='متن مقاله')),
                ('article_register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('article_publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('article_update_date', models.DateField(auto_now=True, verbose_name='تاریخ اخرین آپدیت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت مقاله')),
                ('article_pdf_file', models.CharField(max_length=200, verbose_name='فایل  پی دی اف مقاله')),
                ('article_number_seen', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد بازدید کنندگان')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 't_article',
            },
        ),
        migrations.CreateModel(
            name='Article_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=20, verbose_name='گروه مقاله')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقالات',
                'db_table': 't_group_title',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('family', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('author_image', models.ImageField(upload_to='image/blog_image', verbose_name='تصویر اصلی مقاله')),
                ('author_slug', models.SlugField(max_length=200, verbose_name='کلید نویسنده')),
                ('author_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل نویسنده')),
                ('author_mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه نویسنده')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'db_table': 't_author',
            },
        ),
        migrations.CreateModel(
            name='Key_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=20, verbose_name='کلمه کلیدی')),
            ],
            options={
                'verbose_name': 'کلمه کلیدی',
                'verbose_name_plural': 'کلمات کلیدی',
                'db_table': 't_key_word',
            },
        ),
        migrations.CreateModel(
            name='Article_Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.CharField(max_length=20, verbose_name='تصویر مقاله')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='نام مقاله')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_article_image',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ManyToManyField(to='blog.author', verbose_name='نویسنده مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_key_word',
            field=models.ManyToManyField(to='blog.key_word', verbose_name='کلمه کلیدی'),
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article_group', verbose_name='گروه مقاله'),
        ),
    ]
