# Generated by Django 4.1 on 2022-08-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_main_image',
            field=models.CharField(default='test.jpg', max_length=200, verbose_name='عکس اصلی مقاله'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(upload_to='image/blog_image', verbose_name='تصویر نویسنده'),
        ),
        migrations.AlterField(
            model_name='author',
            name='family',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
    ]
