# Generated by Django 4.1 on 2022-08-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_main_image_alter_author_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_main_image',
            field=models.ImageField(upload_to='image/blog_image', verbose_name='عکس اصلی مقاله'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(upload_to='image/authors', verbose_name='تصویر نویسنده'),
        ),
    ]
