# Generated by Django 4.1 on 2022-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_article_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_gallary',
            name='article_image',
            field=models.ImageField(upload_to='image/blog_image', verbose_name='تصویر مقاله'),
        ),
    ]
