# Generated by Django 4.1 on 2022-08-14 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('information', models.TextField(default='توضیحات', verbose_name='توضیحات')),
                ('place_image', models.ImageField(upload_to='image/places/', verbose_name='عکس')),
                ('visiting_day', models.CharField(max_length=100, verbose_name='روز های بازدید')),
                ('visiting_hour', models.CharField(max_length=100, verbose_name='ساعات بازدید')),
                ('rules', models.TextField(verbose_name='قوانین و مقررات')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
                'db_table': 't_places',
            },
        ),
        migrations.CreateModel(
            name='Visitor_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='نام نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'نوع بازدید کننده',
                'verbose_name_plural': 'نوع بازدید کننده ها',
                'db_table': 't_visitor_type',
            },
        ),
        migrations.CreateModel(
            name='Ticket_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='بهای بیلیط')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='')),
                ('visitor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.visitor_type', verbose_name='')),
            ],
            options={
                'verbose_name': 'قیمت ',
                'verbose_name_plural': 'قیمت ها',
                'db_table': 't_ticket_price',
            },
        ),
    ]
