# Generated by Django 4.1 on 2022-08-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_price',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='ticket_price',
            name='price',
            field=models.IntegerField(default=0, verbose_name='بهای بلیط'),
        ),
        migrations.AlterField(
            model_name='ticket_price',
            name='visitor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.visitor_type', verbose_name='نوع بازدید کننده'),
        ),
        migrations.AlterField(
            model_name='visitor_type',
            name='type_name',
            field=models.CharField(max_length=100, verbose_name='نوع بازدید کننده'),
        ),
    ]
