# Generated by Django 4.1 on 2022-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_ticket_price_place_alter_ticket_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rules',
            field=models.TextField(default='رعایت حجاب اسلامی', verbose_name='قوانین و مقررات'),
        ),
    ]
